#!/bin/bash

echo COMINEZA EJECUCIÓN BORRADO DE DATOS SMNET - CONSULTAR

/sm/postgres/bin/psql -U sm -d fps -c 'SELECT * FROM fps_entidad LIMIT 1'

echo FINALIZA LA EJECUCIÓN DE BORRADO DE DATOS SMNET - CONSULTAR




